# Generated by Django 4.2 on 2023-04-04 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HackathonOrganizers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hackathons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('background_image', models.CharField(max_length=100)),
                ('hackathon_image', models.CharField(max_length=100)),
                ('type_of_submission', models.CharField(max_length=100)),
                ('start_datetime', models.DateTimeField(auto_now_add=True)),
                ('end_datetime', models.DateTimeField(auto_now_add=True)),
                ('reward_prize', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('organized_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.hackathonorganizers')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='HackathonSubmissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=100)),
                ('submission_type', models.CharField(max_length=100)),
                ('submission_file', models.FileField(upload_to='file_upload/')),
                ('submission_url', models.URLField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('hackathon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.hackathons')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.users')),
            ],
        ),
        migrations.CreateModel(
            name='HackathonRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('hackathon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.hackathons')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.users')),
            ],
        ),
    ]
